; This file was automatically generated by ScriptHubImporter.py
<<<<<<< HEAD
global g_ImportsGameVersion64 := 648
global g_ImportsGameVersionPostFix64 := ".2"
global g_ImportsGameVersionPlatform64 := "EGS"
=======
global g_ImportsGameVersion64 := 647
global g_ImportsGameVersionPostFix64 := ".3"
global g_ImportsGameVersionPlatform64 := "Steam"
>>>>>>> 13ce69cecd216521de080c641717890847d51681
